version: 2.1

orbs:
  aws_assume_role: lbh-hackit/aws_assume_role@0.1.0
  node: circleci/node@6.3.0

executors:
  docker-python:
    docker:
      - image: circleci/python:3.7
  node-executor:
    docker:
      - image: cimg/node:24.11-browsers

references:
  workspace_root: &workspace_root '~'
  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

commands:
  assume-role-and-persist-workspace:
    description: 'Assumes deployment role and persists credentials across jobs'
    parameters:
      aws-account:
        type: string
    steps:
      - checkout
      - aws_assume_role/assume_role:
          account: <<parameters.aws-account>>
          profile_name: default
          role: 'LBH_Circle_CI_Deployment_Role'
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - .aws

  remove-lambda:
    description: 'Removes application via Serverless'
    parameters:
      stage:
        type: string
    steps:
      - *attach_workspace
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Remove application
          command: npx --yes serverless remove --stage <<parameters.stage>>

jobs:
  assume-role-dr:
    executor: docker-python
    steps:
      - assume-role-and-persist-workspace:
          aws-account: $AWS_ACCOUNT_DISASTER_RECOVERY

  remove-lambda-dr:
    executor: node-executor
    steps:
      - remove-lambda:
          stage: 'production'

workflows:
  teardown-dr:
    jobs:
      - assume-role-dr:
          context: api-assume-role-disaster-recovery-context
      - remove-lambda-dr:
          context:
            - api-nuget-token-context
            - "Serverless Framework"
          requires:
            - assume-role-dr