version: 2.1

orbs:
  aws_assume_role: lbh-hackit/aws_assume_role@0.1.0
  node: circleci/node@6.3.0
  aws-cli: circleci/aws-cli@5.4.0
  
executors:
  docker-python:
    docker:
      - image: circleci/python:3.7
  node-executor:
    docker:
      - image: cimg/node:24.11-browsers

references:
  workspace_root: &workspace_root '~'
  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

commands:
  assume-role-and-persist-workspace:
    description: 'Assumes deployment role and persists credentials across jobs'
    parameters:
      aws-account:
        type: string
    steps:
      - checkout
      - aws_assume_role/assume_role:
          account: <<parameters.aws-account>>
          profile_name: default
          role: 'LBH_Circle_CI_Deployment_Role'
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - .aws
  deploy-lambda:
    description: 'Deploys application'
    parameters:
      stage:
        type: string
    steps:
      - *attach_workspace
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - aws-cli/install
      - run:
          name: Deploy application
          command: |
            if [ << parameters.stage >> = "production" ]; then
              export NEXT_PUBLIC_GTM_TOKEN_ID=GTM-PWR54HF
            elif [ << parameters.stage >> = "staging" ]; then
              export NEXT_PUBLIC_GTM_TOKEN_ID=GTM-PWLHK3C
            fi

            yarn build
            # Fetch production dependencies
            rm -rf node_modules
            # node_modules specific for lambda.js
            cd lambda
            yarn install --production --frozen-lockfile
            cd ..

            npx --yes serverless deploy --stage <<parameters.stage>>
jobs:
  deploy-to-dr:
    executor: node-executor
    steps:
      - deploy-lambda:
          stage: 'production'

  assume-role-dr:
    executor: docker-python
    steps:
      - assume-role-and-persist-workspace:
          aws-account: $AWS_ACCOUNT_DISASTER_RECOVERY

workflows:
  check-and-deploy-staging-and-production:
    jobs:
      - assume-role-dr:
          context: api-assume-role-disaster-recovery-context
      - deploy-to-dr:
          context: 
            - api-nuget-token-context
            - "Serverless Framework"
          requires:
            - assume-role-dr